build:
  image: golang:1.5
  commands:
    - make deps
    - make build
    - go test

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: mikkeloscar/drone-pkgbuild
    tag: latest
    when:
      branch: master
