language: go

go:
- 1.8

services:
- docker

before_install:
- go get github.com/mattn/goveralls
- go get github.com/Masterminds/glide

install:
- glide install --strip-vendor

script:
- goveralls -service=travis-ci
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- VERSION=latest make build.push

env:
  global:
    DOCKER_EMAIL:
      secure: ifNIh45wgU+29b/9fPYaY+q2i4ZgBWBqExa+gR8CsiNBWvqx9rTj08k8gpGPfTxae80/M5t1KFyR8resukH2+h/KkLLH07f6Bkv7A5mDTLRl867jPvOtaex33lr+bSXKRok3QMBXEjBarSGXtkXAXhzOJR/96RWepl7NEBlKMOzHrhDfVSb3RM2RgEV9oyGeIuNcqPvkjBX5rNXBolWGyN7XaACx2iBNnQLud71FdQo5CGCqb010gROMYkZ10ZJTRkSMwJRAADFRLB0rF2detyT1fCDrl/p1QbxW/rhgkNKKDZNmcTdZ1rb4FtUMZGvGygtRB5BlFh1vNm/LkDBj22cW/y9nIuliEEx3cJPmNIqP2hbZ+njfZkPtOqYECWhpURD0/c2NP16h93KrVbuJdWSGTWcoLWBwvDDirCkRFJegRsgdBxKc3Y4boHaIzmdeYIyfjS/tNa3czNmMychJA5kA37mJrOKsGeZfoYw5gMeFHr+XiT/65pFNlRV3wK2211N5hq+Sdo1Jkpj29aIG5I9+I0u7g0XPSM4KVOJ/cPEEtSJvMzPmMu2r/ROT+UJEz0trYxPeOp/jlgpX+hANz1BlT39m1Djtf7TlLIkBCEZ1xrSvUftoNQnrWv65OGEatPoSYJONrtjT+/4wu5vO7cs5PMLg5z6hDPIm3fPbweQ=
    DOCKER_USER:
      secure: hUuv4ng8uXIPXbKtczTasmhVaKY3xxBnsV45g/nEq7LgB2hzzz5H76eZZRtEDySp6LfbcU/n0O+jAqK2RkiR5dcAa5PMlu0AUfo2v9jWATVGvvGBLJHEe6Cycmda9sJOjx9FTzxaLhnDEOGj3ZtbRhkOeUQlxFiLlEJw2Aoo2t/3PSpHfyP9TiXgRaOhUnFCZLHFz129h/mzisZ6cV6Ok6XAre1UPx684+H8prpBZuwHCG2Dm/ApRaNX5kxhotMwWw0+QfCuqF0jeaKxl/ahHgfIeUPuyQeXG1FSx8qWJ36BtqZT3CtBzSyBuj8JkJafbbTibUJvPayAC1UxfTh3s3ssCXbt4Iy+0/KuPsJgE9ubi5u1J9VuDdMq3ssiZUHpIyjha3GJuChKFEf2MvrTcOYjfyVABsaKfswPF+oXPu9PdwUAWRMJqUdpHuRXi5ScFjEy0LTlKtep0SrpBeNOUNQvdckKMe9POe9nvmy2E5MqzS6B5hdyQYDpGDHFVF3zXBvG3cgFSm5+Aq14egJTfWADlEPqfAFce8LcV5ob2wzkUXfO+oBWJ8mGEtJH50+xVNTtk74HPWVEwX8G4y3FMTS/TsHPHfq+L74K0oeTItVs5c+HptcXluETmQDx1a7Bmu4uKH+lfrlYTJQv+BaOrhQL8E/zFhoXp+WRgGQIp3w=
    DOCKER_PASS:
      secure: ARkR1qLO61NUFpNXq23ThNjeR0hyzWewGOWBS/fDoQVRMrJeIF0AQmhnIec8gSXQoAh3AQRlbv2gJY6n1LnA7hrnmpZygu8ZGgb2utbGytXHYlkFQOwnHIvyafcw9vuO2xUIfioUkj0fYGxdUA2vinITqW4PhvHH9dIZLgv2BmGgvRa/zJuk1nLSD1AjhV3QjtzhnuXb4XmQT4Qomoqa7t2VkkOJywWr13k4444qe27jrbQrrBXZVlWUs5z8GXWspAFACZIK/Y12A3PpOUA3db6pyihHQl1bo1rkASwv5QO0yZNBmlE89xmMpnOmFK0Rp5/NEvnbGBcpa0xxZ2XMzg6U6n7EwpKvi/bShQEJDb5w8kRdVSZPqqMooyaZUGOtXfbfApuu+jUyPtsW9hYGp1JjaFBUG2qVTHWLGNsqIQSfu6MiWKbdgQWAwidpni4AkEjIpUaUAag4T/ZPyg2v34fCY1Rn2gHOAp0o0O/Q8eKXIwgR2uFgY0toFtiCxpfPicNUWxX021G1uD7S4IaUN76Kqfldkfj1W6lHZn8FPbDRM4YVcXwMJWWkIr5JfXUXgt0Tj3FSJSvLL7tC4MDfZ2NsWG0lOE/pmFPpCKfZ6agMaGAahWsPpKETJVy+Er2TYAljFMjLGG4dFWWcc71oymZGZTyFavweiWvn0Q0m7Lc=
