language: go

go:
- 1.8

services:
- docker

before_install:
- go get github.com/mattn/goveralls
- go get github.com/golang/dep/cmd/dep

install:
- dep ensure -v -vendor-only

script:
- goveralls -service=travis-ci
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- VERSION=latest make build.push

env:
  global:
  - secure: nwWyUbMM5NjS0yMHR9Xnoja35c6gyXEtZv+eqABmLVb5gjmBycdWqFe/P4Ui4H60ySl43nzrYH0EJEtiuZxXntBEnKqoonW7LP8uSr2jKI/O0nrGBbBxg2bywb0KAmv8K1SCFwCBkHG0T5w44vB8ejYHRW2TPX7hi9OmdIRWgYvptrmHFU6zSq051aYdA/ZI2YBxyjtRnmV4SckhYhFsj9L3Ou8JC/Je6YRJ/naglDFGRYMppFMjrFutx7trNXNhCWyGpE4glkk9Iaclp+wdNvAyfKzZHprKB6sj80oScOh4ASBnV5tIVL4xu7RyB+LMX5ZCKkQ/1DZFZ9Xod6yt9KQT82X+mhrRdy2cx7cFVL5388bTfnikfoIbCfPPepZcB+49sgIzOMpfBxeF1bqlt4I3EqjzGU2CB9I/qfRdEdFusEJg1nKRgoi5VLFy9a8X9oYoZ6zkNBKVt5/pRY9ekBfYmSSJqTsCXg9ObGJek8cSuif5S5BIeDofTn7pkfm0btXwNw7rMXVWJDduBCO/4fS/cZTagXlR6wdvTT2BiZr9O03JNrhxcpmXofClibl+Ejr4BseM6JlUrmfj2dHdBioVjVX3Ug3kWPB3IOEWk4Os+pnm5rh/lp/FH6oEhOeIZO0brrUlBa98TAqq5cQ9WEy4xpJSY65MaDBuigriTL4=
  - secure: EfyC4bghEAWA5VxNDfyUYCAAPrcsUNplKICtCSSiRDUPalMPFT6GZHyeYgoyW7MWr1jF6V8wSe5LGcfnwiTA3lRWT1uMRBSGvY8p9P+GsIb2Rnvn7IW6Rz6ijf4D4siuz5WucBPRhGbLOTg5qjR9vPNyaR2GuvaOPDGX/+2K3BmPTDjlUyKZ2J2Y6fzjZPoAQqRTevOclXZpvn9+ZqZzaxC5krYmVbipUvdi18lcFM4G6lkaqL2InnB7FxEtESMpE/M76OgpKOJaKpRKLjPxb853LtYosuS+DsMAUrAM5+AzR1Yx/8igI0eLRIOenfFTeLnRPgePAXeee4wsIud/YzBvEeNgimuG57GrlzEzret8Y2qivkR/2eyGurcVGcd543BTXpU6t607uj9Hb3UoKXc94HYA52TJzRuJ8ASLJ9vn6W6jsD183tIXTw1Gkfmt9Z6EDiK6OTn9Q5yirXl5s3DJ7QPPFHutmrMk0WwEjBxJaU34VgPz2nQ+S9RA9hDq4z4NDDkvWO048U0bufkbqapaLF0lM5olfrAcNAxqp3FmmoLNqlQa10Oocjua7S4hvA2wSCD/3bzeXP5/F0epSN1CoMirPCFjdoOy+ydJaVRfmmFaQqLT3hvNnj+o+4GU4XdIdXy1pRtKYOTBENwavl2MYyiLTZQK7KbKSnPfpeI=
