language: go

go:
- 1.8

services:
- docker

before_install:
- go get github.com/mattn/goveralls
- go get github.com/Masterminds/glide

install:
- glide install --strip-vendor

script:
- goveralls -service=travis-ci
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- VERSION=latest make build.push

env:
  global:
    DOCKER_EMAIL:
      secure: ifNIh45wgU+29b/9fPYaY+q2i4ZgBWBqExa+gR8CsiNBWvqx9rTj08k8gpGPfTxae80/M5t1KFyR8resukH2+h/KkLLH07f6Bkv7A5mDTLRl867jPvOtaex33lr+bSXKRok3QMBXEjBarSGXtkXAXhzOJR/96RWepl7NEBlKMOzHrhDfVSb3RM2RgEV9oyGeIuNcqPvkjBX5rNXBolWGyN7XaACx2iBNnQLud71FdQo5CGCqb010gROMYkZ10ZJTRkSMwJRAADFRLB0rF2detyT1fCDrl/p1QbxW/rhgkNKKDZNmcTdZ1rb4FtUMZGvGygtRB5BlFh1vNm/LkDBj22cW/y9nIuliEEx3cJPmNIqP2hbZ+njfZkPtOqYECWhpURD0/c2NP16h93KrVbuJdWSGTWcoLWBwvDDirCkRFJegRsgdBxKc3Y4boHaIzmdeYIyfjS/tNa3czNmMychJA5kA37mJrOKsGeZfoYw5gMeFHr+XiT/65pFNlRV3wK2211N5hq+Sdo1Jkpj29aIG5I9+I0u7g0XPSM4KVOJ/cPEEtSJvMzPmMu2r/ROT+UJEz0trYxPeOp/jlgpX+hANz1BlT39m1Djtf7TlLIkBCEZ1xrSvUftoNQnrWv65OGEatPoSYJONrtjT+/4wu5vO7cs5PMLg5z6hDPIm3fPbweQ=
    DOCKER_USER:
      secure: hUuv4ng8uXIPXbKtczTasmhVaKY3xxBnsV45g/nEq7LgB2hzzz5H76eZZRtEDySp6LfbcU/n0O+jAqK2RkiR5dcAa5PMlu0AUfo2v9jWATVGvvGBLJHEe6Cycmda9sJOjx9FTzxaLhnDEOGj3ZtbRhkOeUQlxFiLlEJw2Aoo2t/3PSpHfyP9TiXgRaOhUnFCZLHFz129h/mzisZ6cV6Ok6XAre1UPx684+H8prpBZuwHCG2Dm/ApRaNX5kxhotMwWw0+QfCuqF0jeaKxl/ahHgfIeUPuyQeXG1FSx8qWJ36BtqZT3CtBzSyBuj8JkJafbbTibUJvPayAC1UxfTh3s3ssCXbt4Iy+0/KuPsJgE9ubi5u1J9VuDdMq3ssiZUHpIyjha3GJuChKFEf2MvrTcOYjfyVABsaKfswPF+oXPu9PdwUAWRMJqUdpHuRXi5ScFjEy0LTlKtep0SrpBeNOUNQvdckKMe9POe9nvmy2E5MqzS6B5hdyQYDpGDHFVF3zXBvG3cgFSm5+Aq14egJTfWADlEPqfAFce8LcV5ob2wzkUXfO+oBWJ8mGEtJH50+xVNTtk74HPWVEwX8G4y3FMTS/TsHPHfq+L74K0oeTItVs5c+HptcXluETmQDx1a7Bmu4uKH+lfrlYTJQv+BaOrhQL8E/zFhoXp+WRgGQIp3w=
    DOCKER_PASS:
    - secure: kljx+ssIwF7db2Oh7jTSJElsNRoX9ksX6ig5mfKX2lBQLIxbcz8eNq40uCel/0ObR6f3/USnOCV8Nj/WJXczGfDQ5Y7zFiNC5AetsNtbh7BksmAXfyk2qa9DqXtkVQuVEpzfFLDuJhPyhbETVDzjYaCK8TLuD4Yx8488vp/LMVHydZ5BovRqKbTVpjAyVKsFnnepSbjRPSageW17QGgRKCl5WIk+Wu/iJsnsLn3nZ8Ud7EGsoCXuKvsD8FuGiH32y9HBClw46T1MeI7EV09P9tryg/ffB7jDlfWoqqQDswEqUQXz6kzE5EhZG4P2m3Y4UcvRVXu4qJfWxLAKXw7VOkR516cy1oSfbOO3OUdISrzWUPBYltE8AP787B19EC7s048wMpGZR3TSM2QLoNkdwhylCQtk3IRtlHNBWlP+dNucAFnhMrNFlVWUWKQKTke69BZoxBKFK+FqL9Ix+/5wNxYtGIZuVo7pxpSnimZiEKDwGgwqf1IMcLlu2NykQ5UDxYH9Du1XozB3kUkDhkJM7RAVeg7rXY3Z5PTwI3YRRmqdzQ3/AdVh/teREIQDa7UhzJav4JjwPDEDnVlMPglesDq5WuNc1vF4Mt0TwOv6lGjW77zm7eDnP6pGBQtw/ITYdO38KhKy6YcvH1+sXvTkuGMr4EaCxBNejySo+8qDYDs=
