language: go

go:
- 1.8

services:
- docker

before_install:
- go get github.com/mattn/goveralls
- go get github.com/Masterminds/glide

install:
- glide install --strip-vendor

script:
- goveralls -service=travis-ci
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- VERSION=latest make build.push

env:
  global:
  - secure: AgW2sCxPEZJqXH6hWFMuMAAJ/+jW2Md0sbR1/MSbuHtE9eZrbHnVHKaAN5FpM4/AeO+YUPu2RKIp9FwMrG4aq7hGvXbSOf1qUzPSwKKYZBXWSy31EbXy3D5nEZwQ3X8oJ9ymqR0hs1L8g41c9ONELjhANpesWSLsYpAPWE8Xg1hzH9V8JV2cf62s00BWTJ8hG4eUv8hfNs6kLWMPMrKvx+SZyueBV7OlMleecMnKIy/sLBdLvP2MieIVlZ+2QopLAJX10xABDmpZf8V9IyS8J42ERKB59tbRMSDMrwose6sOs4087VHjV2n+4+DSRVcSY6ZOLTYerBt5xTQmwAqrEcIq82PJwwHo+i9q9419zhMOnH9FZC6V3b6K2F+/uzKj2Whep5CeDI0wAbtMlJ/cybokahdYjRUbMO1hHFFGZ2xON2boZ4pK9NFAkmH6tEx7DE3BgzTauUX0qu5PgnnmppwfE+HS6VhUboT3AjTGyaL39jxa6lF3rM8oOXCGzpZOb+IlYt01CSVadcR48pjvrQ0MQeAniyWC/x0gk5Kyfvlstg4JE724NNl1xCD4Utyc+aYxJEMXHNPM92UUCxJqtUXRh6VdhGEjE5y+m62R40/IevaBat119SLeMb46XN2sDFQ6LeEFHPIUy92hAGwk8VpvwKGgML88fDyekm07Zmg=
  - secure: nwWyUbMM5NjS0yMHR9Xnoja35c6gyXEtZv+eqABmLVb5gjmBycdWqFe/P4Ui4H60ySl43nzrYH0EJEtiuZxXntBEnKqoonW7LP8uSr2jKI/O0nrGBbBxg2bywb0KAmv8K1SCFwCBkHG0T5w44vB8ejYHRW2TPX7hi9OmdIRWgYvptrmHFU6zSq051aYdA/ZI2YBxyjtRnmV4SckhYhFsj9L3Ou8JC/Je6YRJ/naglDFGRYMppFMjrFutx7trNXNhCWyGpE4glkk9Iaclp+wdNvAyfKzZHprKB6sj80oScOh4ASBnV5tIVL4xu7RyB+LMX5ZCKkQ/1DZFZ9Xod6yt9KQT82X+mhrRdy2cx7cFVL5388bTfnikfoIbCfPPepZcB+49sgIzOMpfBxeF1bqlt4I3EqjzGU2CB9I/qfRdEdFusEJg1nKRgoi5VLFy9a8X9oYoZ6zkNBKVt5/pRY9ekBfYmSSJqTsCXg9ObGJek8cSuif5S5BIeDofTn7pkfm0btXwNw7rMXVWJDduBCO/4fS/cZTagXlR6wdvTT2BiZr9O03JNrhxcpmXofClibl+Ejr4BseM6JlUrmfj2dHdBioVjVX3Ug3kWPB3IOEWk4Os+pnm5rh/lp/FH6oEhOeIZO0brrUlBa98TAqq5cQ9WEy4xpJSY65MaDBuigriTL4=
  - secure: EfyC4bghEAWA5VxNDfyUYCAAPrcsUNplKICtCSSiRDUPalMPFT6GZHyeYgoyW7MWr1jF6V8wSe5LGcfnwiTA3lRWT1uMRBSGvY8p9P+GsIb2Rnvn7IW6Rz6ijf4D4siuz5WucBPRhGbLOTg5qjR9vPNyaR2GuvaOPDGX/+2K3BmPTDjlUyKZ2J2Y6fzjZPoAQqRTevOclXZpvn9+ZqZzaxC5krYmVbipUvdi18lcFM4G6lkaqL2InnB7FxEtESMpE/M76OgpKOJaKpRKLjPxb853LtYosuS+DsMAUrAM5+AzR1Yx/8igI0eLRIOenfFTeLnRPgePAXeee4wsIud/YzBvEeNgimuG57GrlzEzret8Y2qivkR/2eyGurcVGcd543BTXpU6t607uj9Hb3UoKXc94HYA52TJzRuJ8ASLJ9vn6W6jsD183tIXTw1Gkfmt9Z6EDiK6OTn9Q5yirXl5s3DJ7QPPFHutmrMk0WwEjBxJaU34VgPz2nQ+S9RA9hDq4z4NDDkvWO048U0bufkbqapaLF0lM5olfrAcNAxqp3FmmoLNqlQa10Oocjua7S4hvA2wSCD/3bzeXP5/F0epSN1CoMirPCFjdoOy+ydJaVRfmmFaQqLT3hvNnj+o+4GU4XdIdXy1pRtKYOTBENwavl2MYyiLTZQK7KbKSnPfpeI=
